version: '3.4'

volumes:
  npm_data:
  runtime_data:

services:
  scratch-assets:
    container_name: scratch-assets
    image: scratch-assets:latest
    hostname: scratch-assets
    environment:
      - CHOKIDAR_INTERVAL=2500
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
    build:
      context: ./
      dockerfile: Dockerfile
    image: scratch-assets:latest
    command: nodemon --legacy-watch --ignore node_modules --ignore test/ server.js
    volumes:
      - type: bind
        source: ./
        target: /var/app/current
        consistency: cached
        volume:
          nocopy: true
      - npm_data:/var/app/current/node_modules
      - runtime_data:/runtime
      - "./certs:/certs"
    ports:
      - "8557:8557"
    networks:
      - scratch_assets_network
