version: '3.4'

volumes:
  npm_data:
  runtime_data:

services:
  faux3:
    container_name: scratch-faux3
    hostname: faux3
    image: scality/s3server
    ports:
      - "8558:8000"
  scratch-assets:
    container_name: scratch-assets
    hostname: assets
    environment:
      - CHOKIDAR_INTERVAL=2500
    build:
      context: ./
      dockerfile: Dockerfile
    image: scratch-assets:latest
    command: nodemon --legacy-watch --ignore node_modules --ignore test/ server.js
    volumes:
      - type: bind
        source: ./
        target: /var/app/current
        consistency: cached
        volume:
          nocopy: true
      - npm_data:/var/app/current/node_modules
      - runtime_data:/runtime
    ports:
      - "8557:8557"
    depends_on:
      - faux3


